### PR TITLE
Update config to latest consult_template 0.18.2

### PR DESCRIPTION
**Pull request by javierbertoli**
The new config file format is backward-incompatible, and old format will prevent current consul_template from starting.

I just adapted the current parameters so they fit the new format, didn't took too much consideration on keeping backward compatibility.

### CODE REVIEW

**Comment by claflico** [comment]
Just got bit by this myself. Had to downgrade back down to 0.16.0

**Comment by javierbertoli** [comment]
Also, fixed watch and vault fragments order

**Review by craigwatson — CHANGES_REQUESTED** [review]
Hi, thanks for the submission - we'd definitely like to get your fork back in sync, this approach does seem a lot cleaner than individual parameters for config values.

Can you rebase your changes against our current master?

**Comment by javierbertoli** [comment]
@craigwatson, rebased, fixed some conflicts and updated to 0.18.2.

**Comment by craigwatson** [comment]
@javierbertoli it seems that there's a few changes in this PR that don't relate to the `consul_template` version.

If you don't mind, I'm going to close this PR for now. If you can rebase your fork and separate out the versioning changes into a branch, then re-submit a PR containing just those changes, I'll look at getting them merged soon-as.

Apologies for the delay here!

**Pull request closed without merging**
