### PR TITLE
Adapt config file for versions >= 0.18.0

### PR DESCRIPTION
**Pull request by narcisbcn**
Consul-template has changed some blocs within its configuration file for versions >= 0.18.0.
I have some troubles executing your rspec files since it is not compatible with my environment.

### CODE REVIEW

**Comment by narcisbcn** [comment]
I cannot reproduce your beaker environment, I'm using puppet-rspec. I do not see why is that PR failing

**Comment by craigwatson** [comment]
Apologies for the delay - the test failures were down to actual errors in our tests and Gemfile, which have now been fixed.

I'll look into getting this merged as soon as I have time :)

**Comment by joshuaspence** [comment]
Any chance of merging this?

**Review by craigwatson — COMMENTED** [review]
👍

**Pull request merged**
